/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instruments */
        get: operations["list_instruments_api_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Instrument */
        get: operations["get_instrument_api_instruments__instrument_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_api_state_get"];
        put?: never;
        /** Save State */
        post: operations["save_state_api_state_post"];
        /** Delete State */
        delete: operations["delete_state_api_state_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             * @enum {string}
             */
            status: "ok";
        };
        /** Instrument */
        Instrument: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "kit" | "pitched";
            /** Color */
            color: string;
            noteRange: components["schemas"]["NoteRange"] | null;
            /** Samples */
            samples: components["schemas"]["Sample"][];
            /** Defaultnotes */
            defaultNotes: string[];
        };
        /** InstrumentCatalog */
        InstrumentCatalog: {
            /** Instruments */
            instruments: components["schemas"]["Instrument"][];
        };
        /**
         * NoteRange
         * @description Playable range of a pitched instrument, inclusive.
         */
        NoteRange: {
            /** Low */
            low: string;
            /** High */
            high: string;
        };
        /** Project */
        "Project-Input": {
            /**
             * Version
             * @default 2
             */
            version: number;
            /**
             * Name
             * @default Untitled
             */
            name: string;
            /**
             * Bpm
             * @default 120
             */
            bpm: number;
            /**
             * Steps
             * @default 16
             */
            steps: number;
            /**
             * Swing
             * @default 0
             */
            swing: number;
            /**
             * Mastervolume
             * @default 0.8
             */
            masterVolume: number;
            /**
             * Loop
             * @default true
             */
            loop: boolean;
            /** Tracks */
            tracks: components["schemas"]["Track"][];
        };
        /** Project */
        "Project-Output": {
            /**
             * Version
             * @default 2
             */
            version: number;
            /**
             * Name
             * @default Untitled
             */
            name: string;
            /**
             * Bpm
             * @default 120
             */
            bpm: number;
            /**
             * Steps
             * @default 16
             */
            steps: number;
            /**
             * Swing
             * @default 0
             */
            swing: number;
            /**
             * Mastervolume
             * @default 0.8
             */
            masterVolume: number;
            /**
             * Loop
             * @default true
             */
            loop: boolean;
            /** Tracks */
            tracks: components["schemas"]["Track"][];
        };
        /**
         * Sample
         * @description One loadable audio file.
         *
         *     For a kit, ``note`` is the voice id (``kick``). For a pitched
         *     instrument it is the root note name the sampler transposes from.
         */
        Sample: {
            /** Note */
            note: string;
            /** Label */
            label: string;
            /** Url */
            url: string;
        };
        /** Track */
        Track: {
            /** Id */
            id: string;
            /** Instrumentid */
            instrumentId: string;
            /** Note */
            note: string;
            /** Label */
            label: string;
            /** Steps */
            steps: boolean[];
            /**
             * Volume
             * @default 0.8
             */
            volume: number;
            /**
             * Muted
             * @default false
             */
            muted: boolean;
            /**
             * Solo
             * @default false
             */
            solo: boolean;
            effects?: components["schemas"]["TrackEffects"];
        };
        /**
         * TrackEffects
         * @description Per-channel effect chain, normalised to 0..1 by the client.
         */
        TrackEffects: {
            /**
             * Tone
             * @default 1
             */
            tone: number;
            /**
             * Drive
             * @default 0
             */
            drive: number;
            /**
             * Reverb
             * @default 0
             */
            reverb: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_instruments_api_instruments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentCatalog"];
                };
            };
        };
    };
    get_instrument_api_instruments__instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_api_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project-Output"];
                };
            };
        };
    };
    save_state_api_state_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_state_api_state_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
